name: crawler
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py313haa95532_1
  - pip=25.3=pyhc872135_0
  - python=3.13.11=h260b955_100_cp313
  - python_abi=3.13=3_cp313
  - setuptools=80.10.1=py313haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - async-generator==1.10
      - attrs==25.4.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cryptography==46.0.4
      - google-auth==2.48.0
      - google-auth-oauthlib==1.2.4
      - gspread==6.2.1
      - h11==0.16.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - mypy-extensions==1.1.0
      - oauthlib==3.3.1
      - outcome==1.3.0.post0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pysocks==1.7.1
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - selenium==4.40.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - trio==0.32.0
      - trio-typing==0.10.0
      - trio-websocket==0.12.2
      - types-certifi==2021.10.8.3
      - types-urllib3==1.26.25.14
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - websocket-client==1.9.0
      - wsproto==1.3.2
      - zipp==3.23.0
prefix: C:\Users\USER\.anaconda\envs\crawler
